/**:
  ros__parameters:
    # https://docs.ros.org/en/ros2_packages/jazzy/api/joy/index.html#ros-2-driver-for-generic-joysticks-and-game-controllers

    # Axes
    # Following parameters has been tested on PlayStation 4 controller with packages joy and joy_linux.
    LEFT_X: 0
    LEFT_Y: 1
    TRIGGER_LEFT: 2 # index 4 in docs. but 2 in my case?
    RIGHT_X: 3
    RIGHT_Y: 4
    TRIGGER_RIGHT: 5

    # Buttons
    # TODO: needs testing
    A: 0 # Cross
    B: 1 # Square
    X: 2 # Circle
    Y: 3 # Triangle
    BACK: 4 # Select
    GUIDE: 5 # Middle/Manufacturer Button
    START: 6
    STICK_LEFT: 7
    STICK_RIGHT: 8
    SHOULDER_LEFT: 9
    SHOULDER_RIGHT: 10
    DPAD_UP: 11
    DPAD_DOWN: 12
    DPAD_LEFT: 13
    DPAD_RIGHT: 14
    MISC1: 15 # Depends on the controller manufacturer, but is usually at a similar location on the controller as back/start
    PADDLE1: 16 # Upper left, facing the back of the controller if present
    PADDLE2: 17 # Upper right, facing the back of the controller if present
    PADDLE3: 18 # Lower left, facing the back of the controller if present
    PADDLE4: 19 # Lower right, facing the back of the controller if present
    TOUCHPAD: 20 # If present. Button status only


    
